name: Publish

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    name: Publish to NuGet gallery and releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup MSBuild
        run: |
          sudo apt-get install -y nuget mono-devel mono-xbuild

      - name: Restore packages
        run: nuget restore HKModTemplates.csproj

      - name: Package project
        run: dotnet pack --configuration Release -o .
        
      - name: Publish to NuGet gallery
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json -n

      - name: Get NuGet package version
        id: get_version
        run: echo ::set-output name=version::$(find HKModding.HKMod.Templates.*.*.*.nupkg | sed "s/HKModding.HKMod.Templates.//" | sed s/.nupkg//)

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Hollow Knight Mod Templates NuGet Package v${{ steps.get_version.outputs.version }}
          body: "A new version of HKModTemplates has released.\n\nChangelog:\n- "
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: HKModding.HKMod.Templates.${{ steps.get_version.outputs.version }}.nupkg
          asset_name: HKModTemplates.nupkg
          asset_content_type: application/octet-stream